/*
Copyright 2015 The Kubernetes Authors All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_NetworkPolicy = map[string]string{
	"":     "NetworkPolicy represents a network policy.",
	"spec": "Spec defines the desired behavior for this NetworkPolicy.",
}

func (NetworkPolicy) SwaggerDoc() map[string]string {
	return map_NetworkPolicy
}

var map_NetworkPolicyIngressRule = map[string]string{
	"":      "This NetworkPolicyIngressRule matches traffic if and only if the traffic matches both Ports AND From.",
	"ports": "List of ports which should be made accessible on the pods selected by PodSelector. Each item in this list is combined using a logical OR. If this field is nil, this NetworkPolicyIngressRule matches all ports (traffic not restricted by Port). If this field is non-nil but contains no items, this NetworkPolicyIngressRule matches no ports (no traffic matches). If this field is non-nil and contains at least one item, then this NetworkPolicyIngressRule allows traffic only if the traffic matches at least one NetworkPolicyPort in the Ports list.",
	"from":  "List of sources which should be able to access the pods selected by PodSelector. Items in this list are combined using a logical OR operation. If this field nil, this NetworkPolicyIngressRule matches all sources (traffic not restricted by source). If this field is non-nil but contains no items, this NetworkPolicyIngressRule matches no sources (no traffic matches). If this field is non-nil and contains at least on item, this NetworkPolicyIngressRule allows traffic only if the traffic matches at least one NetworkPolicyPeer in the From list.",
}

func (NetworkPolicyIngressRule) SwaggerDoc() map[string]string {
	return map_NetworkPolicyIngressRule
}

var map_NetworkPolicyList = map[string]string{
	"": "NetworkPolicyList is a collection of NetworkPolicys.",
}

func (NetworkPolicyList) SwaggerDoc() map[string]string {
	return map_NetworkPolicyList
}

var map_NetworkPolicyPeer = map[string]string{
	"pods":       "If 'Namespaces' is defined, 'Pods' must not be. This is a label selector which selects Pods in this namespace. This NetworkPolicyPeer matches any pods selected by this selector. This field follows standard unversioned.LabelSelector semantics. If nil, this selector selects no pods. If non-nil but empty, this selector selects all pods in this namespace.",
	"namespaces": "If 'Pods' is defined, 'Namespaces' must not be. Selects Kubernetes Namespaces.  This NetworkPolicyPeer matches all pods in all namespaces selected by this label selector. This field follows standard unversioned.LabelSelector semantics. If nil, this selector selects no namespaces. If non-nil but empty, this selector selects all namespaces.",
}

func (NetworkPolicyPeer) SwaggerDoc() map[string]string {
	return map_NetworkPolicyPeer
}

var map_NetworkPolicyPort = map[string]string{
	"protocol": "The protocol (TCP or UDP) which traffic must match. If not defined, this field defaults to TCP.",
	"port":     "If specified, the port on the given protocol.  This can either be a numerical or named port.  If this field is nil, this NetworkPolicyPort matches all port names and numbers. If non-nil, only traffic on the specified protocol AND port will be matched by this NetworkPolicyPort.",
}

func (NetworkPolicyPort) SwaggerDoc() map[string]string {
	return map_NetworkPolicyPort
}

var map_NetworkPolicySpec = map[string]string{
	"":            "A NetworkPolicySpec is the specification of a NetworkPolicy.",
	"podSelector": "Selects the pods to which this NetworkPolicy object applies.  The array of NetworkPolicyIngressRules below is applied to any pods selected by this field. Multiple NetworkPolicy objects can select the same set of pods.  In this case, the NetworkPolicyRules for each are combined additively. This field is NOT optional and follows standard unversioned.LabelSelector semantics. An empty PodSelector matches all pods in this namespace.",
	"ingress":     "List of ingress rules to be applied to the selected pods. Traffic is allowed to a pod if Namespace.NetworkPolicy.Ingress.Isolation is undefined, OR if the traffic source is the pod's local kubelet (for health checks), OR if the traffic matches at least one NetworkPolicyIngressRule across all of the NetworkPolicy objects whose podSelector matches the pod. If this field is nil, this NetworkPolicy does not affect ingress to the selected pods. If this field is non-nil but contains no rules, this NetworkPolicy allows no traffic. If this field is non-nil and contains at least one rule, this NetworkPolicy allows any traffic which matches at least one of the NetworkPolicyIngressRules in this list.",
}

func (NetworkPolicySpec) SwaggerDoc() map[string]string {
	return map_NetworkPolicySpec
}

// AUTO-GENERATED FUNCTIONS END HERE
